services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: camsight-backend
    ports:
      - "${EXPOSED_BACKEND_PORT}:${BACKEND_PORT}"
    restart: unless-stopped
    networks:
      - camsight-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${BACKEND_PORT}/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: camsight-frontend
    ports:
      - "${EXPOSED_FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - camsight-network

networks:
  camsight-network:
    driver: bridge