services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: camsight-backend
    ports:
      - "8001:8000"
    restart: unless-stopped
    networks:
      - camsight-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: camsight-frontend
    ports:
      - "3006:3000"
    environment:
      - BACKEND_HOST=backend
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - camsight-network

networks:
  camsight-network:
    driver: bridge
